# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'account_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class accountDialog(object):
    def setupUi(self, accountDialog):
        accountDialog.setObjectName("accountDialog")
        accountDialog.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(accountDialog)
        self.gridLayout.setContentsMargins(50, 30, 50, 30)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(30)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(accountDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.teacherName_label = QtWidgets.QLabel(accountDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teacherName_label.sizePolicy().hasHeightForWidth())
        self.teacherName_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.teacherName_label.setFont(font)
        self.teacherName_label.setObjectName("teacherName_label")
        self.horizontalLayout_2.addWidget(self.teacherName_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(accountDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.module_label = QtWidgets.QLabel(accountDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.module_label.sizePolicy().hasHeightForWidth())
        self.module_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.module_label.setFont(font)
        self.module_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.module_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.module_label.setObjectName("module_label")
        self.horizontalLayout.addWidget(self.module_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.logout_pushButton = QtWidgets.QPushButton(accountDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logout_pushButton.sizePolicy().hasHeightForWidth())
        self.logout_pushButton.setSizePolicy(sizePolicy)
        self.logout_pushButton.setMaximumSize(QtCore.QSize(150, 80))
        self.logout_pushButton.setObjectName("logout_pushButton")
        self.horizontalLayout_3.addWidget(self.logout_pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(accountDialog)
        QtCore.QMetaObject.connectSlotsByName(accountDialog)

    def retranslateUi(self, accountDialog):
        _translate = QtCore.QCoreApplication.translate
        accountDialog.setWindowTitle(_translate("accountDialog", "Dialog"))
        self.label.setText(_translate("accountDialog", "Teacher:"))
        self.teacherName_label.setText(_translate("accountDialog", "TextLabel"))
        self.label_3.setText(_translate("accountDialog", "Module:"))
        self.module_label.setText(_translate("accountDialog", "TextLabel"))
        self.logout_pushButton.setText(_translate("accountDialog", "Confirm Logout"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = accountDialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

