# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/derrickyu/Downloads/GRP17-master/resources/UI_resources/recordedSession_Frame1.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class recordedSession_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(672, 530)
        self.gridLayout = QtWidgets.QGridLayout(Frame)
        self.gridLayout.setContentsMargins(30, 30, 30, 30)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(50)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.teachingSessionName_label = QtWidgets.QLabel(Frame)
        self.teachingSessionName_label.setAlignment(QtCore.Qt.AlignCenter)
        self.teachingSessionName_label.setObjectName("teachingSessionName_label")
        self.verticalLayout_2.addWidget(self.teachingSessionName_label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(50, -1, 0, -1)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(Frame)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.teacherName_label = QtWidgets.QLabel(Frame)
        self.teacherName_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.teacherName_label.setObjectName("teacherName_label")
        self.horizontalLayout.addWidget(self.teacherName_label)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 10)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(Frame)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.sessionName_label = QtWidgets.QLabel(Frame)
        self.sessionName_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.sessionName_label.setObjectName("sessionName_label")
        self.horizontalLayout_2.addWidget(self.sessionName_label)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 10)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(Frame)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.teachingVenue_label = QtWidgets.QLabel(Frame)
        self.teachingVenue_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.teachingVenue_label.setObjectName("teachingVenue_label")
        self.horizontalLayout_3.addWidget(self.teachingVenue_label)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 10)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(Frame)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.attendance_label = QtWidgets.QLabel(Frame)
        self.attendance_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.attendance_label.setObjectName("attendance_label")
        self.horizontalLayout_4.addWidget(self.attendance_label)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 10)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.absentStudent_horizontalLayout = QtWidgets.QHBoxLayout()
        self.absentStudent_horizontalLayout.setContentsMargins(-1, -1, 200, 100)
        self.absentStudent_horizontalLayout.setObjectName("absentStudent_horizontalLayout")
        self.label_10 = QtWidgets.QLabel(Frame)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_10.setObjectName("label_10")
        self.absentStudent_horizontalLayout.addWidget(self.label_10)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.absentStudent_textBrowser = QtWidgets.QTextBrowser(Frame)
        self.absentStudent_textBrowser.setStyleSheet("background-color: transparent;border-style: transparent")
        self.absentStudent_textBrowser.setObjectName("absentStudent_textBrowser")
        self.verticalLayout_3.addWidget(self.absentStudent_textBrowser)
        self.verticalLayout_3.setStretch(0, 1)
        self.absentStudent_horizontalLayout.addLayout(self.verticalLayout_3)
        self.absentStudent_horizontalLayout.setStretch(0, 1)
        self.absentStudent_horizontalLayout.setStretch(1, 10)
        self.verticalLayout.addLayout(self.absentStudent_horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.teachingSessionName_label.setText(_translate("Frame", "TeachingSessionName"))
        self.label_2.setText(_translate("Frame", "Teacher Name:"))
        self.teacherName_label.setText(_translate("Frame", "TextLabel"))
        self.label_4.setText(_translate("Frame", "Session Name:"))
        self.sessionName_label.setText(_translate("Frame", "TextLabel"))
        self.label_6.setText(_translate("Frame", "Teaching Venue:"))
        self.teachingVenue_label.setText(_translate("Frame", "TextLabel"))
        self.label_8.setText(_translate("Frame", "Attendance:"))
        self.attendance_label.setText(_translate("Frame", "TextLabel"))
        self.label_10.setText(_translate("Frame", "Absent Student:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
